### ISSUE TITLE
CONTINUABLE_WITH_UNHANDLED_EXCEPTION

### ISSUE THREAD

**Issue by wenqzheng** [Naios/fluent.cpp#36] opened 2020-08-27 03:38 UTC
@Naios 

Hello,
    when I apply a continuable_base to_future(),"Illegal instruction" happens! Then I find it's something about CONTINUABLE_WITH_UNHANDLED_EXCEPTION. Now, I'm confused about CONTINUABLE_WITH_UNHANDLED_EXCEPTION. Why this happen? Thanks!

-----

### Commit Hash

{Please write here}

### Expected Behavior

{Please write here}

### Actual Behavior

{Please write here}

### Steps to Reproduce

{Please write here}

### Your Environment

- OS: {Please write here - Windows/Linux dist/OSX}
- Compiler and version: {Please write here - MSVC/Clang/GCC/Other}
- Standard library (if non default): {Please write here}

**Comment by Naios** [comment] 2020-08-27 16:30
Your issue is **missing important information** such as:
- A minimal reproducible example
- A detailed description of what you have tried to accomplish
- The actual behaviour and which behaviour you have expected

Please make sure to fill the required fields of the issue template.
Otherwise your issue can't be processed, thank you in advance.

Also make sure to link against `pthread` on linux.

**Comment by Naios** [comment] 2020-09-02 18:59
Since there was no further activity on this issue I'm marking it as resolved.
If you encounter any new bugs or questions open a new issue please.

**Closed as completed by Naios** 2020-09-02 18:59 UTC

**Comment by Spongman** [comment] 2022-09-22 06:50
I just ran into this and it's caused by allowing unhandled exceptions to leak out of the end of your coroutine chain. this can be avoided by adding final `.fail()` clause to trap these unhandled exceptions.

**Comment by Naios** [comment] 2022-09-22 07:28
@Spongman could you open a separate ticket for this issue please?

**Comment by Spongman** [comment] 2022-09-22 07:32
I don't actually think it's an issue in the library. I was just using it wrong (not handling all exceptions correctly), and that was what was causing the Illegal Instruction (which is triggered by `CTI_DETAIL_TRAP()`) and I wanted to add comment to this issue in case anyone else ran into the same thing.
